import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalBottomBar from "@/components/ConditionalBottomBar";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Health App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-200`}
      >
        {/* จัด layout ให้อยู่กลางจอ */}
        <div className="flex justify-center items-center min-h-screen">
          {/* กรอบมือถือ */}
          <div className="relative bg-gray-100 w-full max-w-sm min-h-screen shadow-lg overflow-hidden">
            {/* Topbar */}
            <div className="bg-orange-400 py-4 px-4 font-serif font-bold flex justify-between items-center">
              <nav className="text-xl">Thaihealth</nav>
              <div className="bg-amber-50 flex gap-2 px-3 rounded-full py-1 items-center">
                <Image src="/topbar/coin.png" width={24} height={24} alt="coin" />
                <span className="text-lg">100</span>
              </div>
            </div>

            {/* เนื้อหาหลัก */}
            <main className="pb-24">{children}</main>

            {/* Bottombar */}
            <div className="absolute bottom-0 w-full">
              <ConditionalBottomBar />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}