import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalBottomBar from "@/components/ConditionalBottomBar";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-orange-400 py-4 p-4 font-serif font-bold flex justify-between">
        <nav className="text-xl">Thaihealth</nav>
        <div className="bg-amber-50 flex gap-4 px-2 rounded-full py-2">
          <Image src="/topbar/coin.png" width={30} height={24} alt="coin"/>
          <div className="text-lg">100</div>
        </div>
        </div>
        {children}
        <ConditionalBottomBar/>
      </body>
    </html>
  );
}
