import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ConditionalBottomBar from "@/components/ConditionalBottomBar";
import { LiffProvider } from "@/contexts/LiffContext";
import UserPicture from "@/components/profile/UserPicture";
import AuthRedirector from "@/components/AuthRedirector"; // Added import for AuthRedirector

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Health App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-secondary`}
      >
        <div className="flex bg-gray-50 justify-center items-center min-h-screen">
          <div className="relative bg-background w-full max-w-sm h-screen shadow-lg flex flex-col bg-gray-100 overflow-hidden">
            {/* Topbar */}
            <div className="bg-[#9337E8] text-primary-foreground py-4 px-4 font-serif font-bold flex items-center shrink-0">
              <nav className="text-xl text-gray-100">TUH Health Promotion</nav>
            </div>

            {/* Main Content */}
            <main className="flex-1 overflow-y-auto">
              <LiffProvider>
                <AuthRedirector>{children}</AuthRedirector>
              </LiffProvider>
            </main>

            {/* Bottombar */}
            <div className="w-full shrink-0">
              <ConditionalBottomBar />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}